version: "3.8"
services:
  streamlit:
    build: .
    container_name: streamlit_app
    expose:
      - "8501"
    restart: always

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - streamlit

volumes:
  caddy_data:
  caddy_config:
